---
title: "My summer R coding notes"
author: "rp"
date: "8/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The following function displays packages that are loaded in the R environment.
```{r}
my_packages <- library()$results[,1]
head(my_packages, 10)
```
```{r}
my_packages
```


To install `phyloch` we will use the package `devtools`.
```{r}
install.packages("devtools")
```

Then we can install `phyloch` from Github.
```{r eval= FALSE}
devtools::install_github("fmichonneau/phyloch")
#ERROR: lazy loading failed for package 'phyloch'
#* removing 'C:/Users/randy/OneDrive/Documents/R/win-library/4.0/phyloch'
```

## Build my R package into a website

We will use the `pkgdown` package for this

Instructions from  https://pkgdown.r-lib.org/

Get started with usethis:

```{r eval=FALSE}
# Run once to configure your package to use pkgdown
usethis::use_pkgdown()
```

Use pkgdown to update your website:

```{r eval=FALSE}

# Run to build the website
pkgdown::build_site()
```

